[theme]
base="light"
#primaryColor="slateBlue"    # button color sidebar
#primaryColor="#4093D4"
#primaryColor="#57b0a4"
primaryColor="#2f6d80"
##primaryColor="#134044"


#backgroundColor="mintCream"
backgroundColor="#e1e7e0"
#backgroundColor="#fdfdfb"


textColor="#2b4560"
#textColor="#134044"


#secondaryBackgroundColor="darkSeaGreen"
#secondaryBackgroundColor="#57b0a4"
secondaryBackgroundColor="floralwhite"

baseRadius="full"

[theme.sidebar]
#backgroundColor="lavender"
#backgroundColor="#0A0F3D"
backgroundColor="#6aa4b0"
#backgroundColor="#30787F"


baseRadius="none"
